<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

// use Illuminate\Notifications\Notifiable;
// use Illuminate\Foundation\Auth\User as Authenticatable;

class Npo_register extends Model
{
    protected $fillable = [
        'id',
        'npo_name', 
        'title', 
        'subtitle',
        'url', 
        'embed_youtube',
        'blue_card_title',
        'blue_card_body',
        'green_card_titel',
        'green_card_body',
        'yellow_card_title',
        'yellow_card_body',
        'code1', 
        'code2', 
        'cord3', 
        'manager', 
        'member1', 
        'member1_pic',
        'member1_pos',
        'member1_detail',
        'member1_twitter',
        'member1_facebook',
        'member1_insta',
        'member1_youtube',
        'member1_linkedin',
        'member2', 
        'member2_pic',
        'member2_pos',
        'member2_detail',
        'member2_twitter',
        'member2_facebook',
        'member2_insta',
        'member2_youtube',
        'member2_linkedin',
        'member3', 
        'member3_pic',
        'member3_pos',
        'member3_detail',
        'member3_twitter',
        'member3_facebook',
        'member3_insta',
        'member3_youtube',
        'member3_linkedin',
        'member4', 
        'member4_pic',
        'member4_pos',
        'member4_detail',
        'member4_twitter',
        'member4_facebook',
        'member4_insta',
        'member4_youtube',
        'member4_linkedin',
        'member5', 
        'member5_pic',
        'member5_pos',
        'member5_detail',
        'member5_twitter',
        'member5_facebook',
        'member5_insta',
        'member5_youtube',
        'member5_linkedin',
        'member6', 
        'member6_pic',
        'member6_pos',
        'member6_detail',
        'member6_twitter',
        'member6_facebook',
        'member6_insta',
        'member6_youtube',
        'member6_linkedin',
        'member7', 
        'member7_pic',
        'member7_pos',
        'member7_detail',
        'member7_twitter',
        'member7_facebook',
        'member7_insta',
        'member7_youtube',
        'member7_linkedin',
        'member8', 
        'member8_pic',
        'member8_pos',
        'member8_detail',
        'member8_twitter',
        'member8_facebook',
        'member8_insta',
        'member8_youtube',
        'member8_linkedin',
        'member9', 
        'member9_pic',
        'member9_pos',
        'member9_detail',
        'member9_twitter',
        'member9_facebook',
        'member9_insta',
        'member9_youtube',
        'member9_linkedin',
        'member10', 
        'member10_pic',
        'member10_pos',
        'member10_detail',
        'member10_twitter',
        'member10_facebook',
        'member10_insta',
        'member10_youtube',
        'support_limit',
        'support_contents', 
        'support_contents_detail', 
        'support_amount', 
        'body', 
        'published'
    ];
    // public function edit() {
    //     return $this->edit('App\Npo_register');
    // }
}
